before_install:
  - gem update bundler

bundler_args: --without development

cache: bundler

env:
  global:
    - JRUBY_OPTS="$JRUBY_OPTS --debug"

language: ruby

rvm:
  - 2.4.1

matrix:
  allow_failures:
    - rvm: 1.8.7
    - rvm: jruby-head
    - rvm: ruby-head
  fast_finish: true

sudo: false
